changelog:
  categories:
    - title: "🚀 Features"
      labels: 
        - "feature"
        - "feat"
        - "enhancement"
        - "type: feature"
    - title: "🐛 Bug Fixes"
      labels: 
        - "fix"
        - "bug"
        - "bugfix"
        - "hotfix"
        - "type: fix"
    - title: "📚 Documentation"
      labels:
        - "docs"
        - "documentation"
        - "readme"
        - "type: docs"
    - title: "⚡ Performance"
      labels: 
        - "perf"
        - "performance"
        - "optimization"
        - "type: perf"
    - title: "🏗️ Build"
      labels:
        - "build"
        - "ci"
        - "deployment"
        - "type: build"
    - title: "🎨 Style"
      labels:
        - "style"
        - "formatting"
        - "lint"
        - "type: style"
    - title: "🔧 Chores"
      labels: 
        - "chore"
        - "maintenance"
        - "refactor"
        - "type: chore"
        - "type: refactor"
    - title: "📦 Dependencies"
      labels:
        - "dependencies"
        - "deps"
        - "requirements"
        - "type: deps"
    - title: "🔒 Security"
      labels:
        - "security"
        - "vulnerability"
        - "cve"
        - "type: security"
    - title: "🧪 Testing"
      labels:
        - "test"
        - "testing"
        - "type: test"
    - title: "🔄 Other"
      labels: 
        - "*"
  exclude:
    labels:
      - "skip-changelog"
      - "no-changelog"
      - "ignore"
      - "duplicate"
      - "invalid"
      - "wontfix"
